services:
  web:
    build:
      context: .
    container_name: recommandationApi
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/apiRecommandation
    environment:
      - DJANGO_SETTINGS_MODULE=recommendation_project.settings
